### ISSUE TITLE
No heading status update when text is marked directly without clicking first

### ISSUE THREAD

**Issue by rugk** [ether/ep_headings2#11]
STR:
1. Mark some usual (non-heading) text.
2. Change the heading.
3. Without clicking anywhere else, mark another text part.

What happens: The headings status still shows the heading you selected in 2.

What should happen: read the new heading status and show it. (In this case: "normal")

This makes changing headlines after each other very difficult as you always have to click once before you can mark another headline.

**Comment by JohnMcLear** [comment]
How are you marking the second text without clicking?  By using shift and arrow keys?

**Comment by rugk** [comment]
I guess so…  :shrug:  this is nearly 4 years ago… :roll_eyes: 

Maybe I just meant that you instantly click and "drag" (and drop) the cursor.
So you do not "de-focus" the headline before.

**Comment by JohnMcLear** [comment]
I don't really understand to be honest..  Can you get a gif of it happening?

**Comment by JohnMcLear** [comment]
Closing as unable to replicate.
