### ISSUE TITLE
Cannot update multiple headlines at once

### ISSUE THREAD

**Issue by rugk** [ether/ep_headings2#12]
STR: Mark multiple text parts at one (Ctrl+select) and try to change the headline.

What happens: Only the first selected text part in the document is changed.

What should happen: Chan ge all selected text parts (at once).

Together with https://github.com/JohnMcLear/ep_headings2/issues/11 this makes changing multiple headlines difficult.

**Comment by JohnMcLear** [comment]
I don't think Etherpad is event aware of having multiple "sel" events, tbh I never used this feature/functionality and I don't think Etherpad supports it.  Pretty interesting though!

**Comment by JohnMcLear** [comment]
Edge and Chrome don't support multiple selections.  So I'm not sure it's worth exploring this as it would be a firefox only feature?

**Comment by rugk** [comment]
:shrug:
