### ISSUE TITLE
HTML Export problem : discarded style (heading 2/3/..) in list items

### ISSUE THREAD

**Issue by guillaume-uH57J9** [ether/ep_headings2#15]
Greeting,

When applying some style (heading 2, heading 3, ...) to items in a list, and exporting to HTML, the style is discarded. 

Etherpad view:

![etherpad-edit](https://cloud.githubusercontent.com/assets/4953748/19855089/01971944-9f73-11e6-83fb-ee4936cb2f70.png)

Exported HTML view:

![etherpad-html-export](https://cloud.githubusercontent.com/assets/4953748/19855099/08aecf42-9f73-11e6-8cc6-e3f8330f7c3d.png)

Exported HTML snippet: 

`<ul class="bullet"><li>List level 1</li><ul class="bullet"><li>List level 2</li><li>List level 2</li></ul></ul>`

**Comment by guillaume-uH57J9** [comment]
This was originally filed as an etherpad-lite issue but closed with the comment: "Plugin problem, please create the bug reports on the plugins."

https://github.com/ether/etherpad-lite/issues/3068

**Comment by JohnMcLear** [comment]
Resolved.
