### ISSUE TITLE
Export: Headers don't export correctly

### ISSUE THREAD

**Issue by spctrlth** [ether/ep_headings2#20]
Hey,

We've got an etherpad instance running with plug-ins markdown v0.0.10, mediawiki v0.0.7 and headings2 v0.0.9

When we want to export, we notice the headings aren't exported correctly.
* The output the text just has a star in front of the headings for export to html, odt, pdf, doc and mediawiki.
* In markdown (not sure if the problem is here or in the markdown plug-in) the headings 1, 2 and 3 are correct, but 4, 5 and 6 use spaces instead of prefixing `#`. Heading4 has four spaces, Heading5 has six spaces, Heading6 has eight spaces.

Example for html:
1. We create a pad and add headings (e.g. text Heading1 and format it as Heading1...)
2. Export to html

We expect something like
`<h1>Heading1</h1><h2>Heading2</h2><h3>Heading3</h3>`

But we get
`*Heading1<br>*Heading2<br>*Heading3<br>`

**Comment by Hiswe** [comment]
Have you tried installing the latest plugin version (not the one published on NPM) like here:

https://github.com/ether/ep_headings2/issues/19#issuecomment-472317881
