### ISSUE TITLE
[Display bug] Arrow overlaps heading number in dropdown

### ISSUE THREAD

**Issue by Oremountainflorian** [ether/ep_headings2#26]
Applies to german language setting

## System

OS: Windows 8.1
Browser: Firefox 76 / Chrome 81
Etherpad version: 1.8.4

## Screenshot 

![grafik](https://user-images.githubusercontent.com/44228345/82047256-ca43af80-96b2-11ea-9362-5d8d32870fdb.png)

**Comment by JohnMcLear** [comment]
@seballot  :)

**Comment by seballot** [comment]
Hi ! thanks, solved here : https://github.com/ether/etherpad-lite/pull/4017
