### ISSUE TITLE
[Display bug] Some characters of heading in upper line are overlapped by color in line below

### ISSUE THREAD

**Issue by Oremountainflorian** [ether/ep_headings2#27]
## Problem description

When authorship color is on and you have an heading 1/2/4 over more than 1 line, some characters overlap of the upper line are overlapped by the authorship color in the line below

![grafik](https://user-images.githubusercontent.com/44228345/82047559-4b9b4200-96b3-11ea-99d8-35234a72a843.png)

**Comment by JohnMcLear** [comment]
@seballot  🍡

**Comment by seballot** [comment]
same, solved here : https://github.com/ether/etherpad-lite/pull/4017

Thanks for the clear issue report
