### ISSUE TITLE
Unicode issues after export

### ISSUE THREAD

**Issue by vasylOstrovskyi** [ether/ep_headings2#39]
Formatted text is broken after export to .doc, .pdf. .odt. Example. I type the same text in Engilsh and Ukrainian twice:
Sample text. Якийсь текст.
Sample text. Якийсь текст.
Then I format the first line as heading. Then I export the result to one of the listed formats. In the exported file I have:
Sample text. Ð¯ÐºÐ¸Ð¹ÑÑŒ Ñ‚ÐµÐºÑÑ‚.
Sample text. Якийсь текст.
The formated text is broken, unformatted is saved correctly. The same for pdf and odt
Export to html, plain text and markdown works correct.

Regards,
 Vasyl

**Comment by JohnMcLear** [comment]
Cc @ilmartyrk

**Comment by JohnMcLear** [comment]
Works fine for me.

root@loadtest:/home/pi/lintdemo/etherpad-lite/node_modules# /usr/bin/soffice --version
LibreOffice 5.2.7.2 20m0(Build:2)

latest develop branch of etherpad

git cloned ep_headings2.

**Comment by JohnMcLear** [comment]
![image](https://user-images.githubusercontent.com/220864/102921625-96b8d700-4484-11eb-9a22-2bf9bd3d6191.png)

**Comment by vasylOstrovskyi** [comment]
Strange... Is that **exported** to pdf or doc?
I have latest develop etherpad-lite, libreoffice 6.2.8.2 20(Build:2) and headings2 0.2.12 installed by plugin manager (to be sure, I cloned git repository and compared files - no difference), node 12.20.0
Also I noticed that if I export to html, the output contains the following:
`<h1>Якийсь текст</h1><br>&#1071;&#1082;&#1080;&#1081;&#1089;&#1100; &#1090;&#1077;&#1082;&#1089;&#1090;<br>`
so that formatted text is expotred as is, while non-formatted is encoded. It looks that libreoffice treats text as ascii instead of unicode

Regards,
 Vasyl

**Comment by JohnMcLear** [comment]
yes exported and I tried pdf doc and odt.

**Comment by JohnMcLear** [comment]
My HTML looks like this:

```

  | <!doctype html>
-- | --
  | <html lang="en">
  | <head>
  | <title>dFhsqQBzyPvN8-tDFqbx</title>
  | <meta name="generator" content="Etherpad">
  | <meta name="author" content="Etherpad">
  | <meta name="changedby" content="Etherpad">
  | <meta charset="utf-8">
  | <style>
  | ol {
  | counter-reset: item;
  | }
  |  
  | ol > li {
  | counter-increment: item;
  | }
  |  
  | ol ol > li {
  | display: block;
  | }
  |  
  | ol > li {
  | display: block;
  | }
  |  
  | ol > li:before {
  | content: counters(item, ".") ". ";
  | }
  |  
  | ol ol > li:before {
  | content: counters(item, ".") ". ";
  | margin-left: -20px;
  | }
  |  
  | ul.indent {
  | list-style-type: none;
  | }
  |  
  | h1{font-size: 2.5em;}
  | h2{font-size: 1.8em;}
  | h3{font-size: 1.5em;}
  | h4{font-size: 1.2em;}
  | code{font-family: RobotoMono;}
  |  
  | </style>
  | </head>
  | <body>
  | <h1>&#1071;&#1082;&#1080;&#1081;&#1089;&#1100; &#1090;&#1077;&#1082;&#1089;&#1090;</h1><br><h2>&#1071;&#1082;&#1080;&#1081;&#1089;&#1100; &#1090;&#1077;&#1082;&#1089;&#1090;</h2><br><h3>&#1071;&#1082;&#1080;&#1081;&#1089;&#1100; &#1090;&#1077;&#1082;&#1089;&#1090;</h3><br><h4>&#1071;&#1082;&#1080;&#1081;&#1089;&#1100; &#1090;&#1077;&#1082;&#1089;&#1090;</h4><br>e<br><code>&#1071;&#1082;&#1080;&#1081;&#1089;&#1100; &#1090;&#1077;&#1082;&#1089;&#1090;</code><br>e<br>
  | </body>
  | </html>
  |  

```

**Comment by JohnMcLear** [comment]
So I'm unable to replicate this bug ;\

**Comment by vasylOstrovskyi** [comment]
OK, seems that it was some misconfiguration in my setup. Most likely wrong 'lang' setting (for javascript, 'uk-ua' is wrong and 'uk' should be used). I did something else which I cannot reproduce, and now the plugin works properly.
Thanks for your support.
 Vasyl
