### ISSUE TITLE
Compatibility with Etherpad 1.8.7

### ISSUE THREAD

**Issue by lucaguindani** [ether/ep_headings2#40]
Looks like the plugin is not yet compatible with Etherpad 1.8.7.

I get the following error when I use the plugin in a pad (however heading is applied successfully). I use the latest version of ep_headings2 (0.2.13).

```UNSETTLED FUNCTION BUG IN HOOK FUNCTION (plugin: ep_headings2, function name: ep_headings2/static/js/index, hook: aceEditEvent): The hook function neither called the callback nor returned a non-undefined value. This is prohibited because it will result in freezes when a future version of Etherpad updates the hook to support asynchronous behavior.```

**Comment by JohnMcLear** [comment]
Every plugin does this, it's an issue within Etherpad

The plugin is fine.
