### ISSUE TITLE
Button Icon is missing

### ISSUE THREAD

**Issue by lisandi** [ether/ep_headings2#51]
It would be great and more useful to display a Button Icon in the Button bar instead of the Text which clutters the "Button" Bar. A click on the Button could open up the Menu so people can choose from it. The chosen format could get highlighted as replacing it with a long text would crash the Button bar completely.

By Hover or longer Tapping with the finger (on tablet/phone), the actual chosen value could be shown in the title tag.
![Screen Shot 2021-10-01 at 19 37 27](https://user-images.githubusercontent.com/1982011/135620902-c1b6ac1f-fccb-4e5a-934c-fac3352f0b73.png)

**Comment by JohnMcLear** [comment]
See other responses requesting same thing.
