### ISSUE TITLE
Export: Headings "override" all formatting

### ISSUE THREAD

**Issue by rugk** [ether/ep_headings2#9]
In headings all formatting options (things like font family and color [from other plugins], but also build-in things such as _italic_ or ~~strikethrough~~) are removed/not exported.

See https://github.com/JohnMcLear/ep_font_color/issues/8#issuecomment-219236322

**Comment by lpagliari** [comment]
On https://github.com/JohnMcLear/ep_headings2/blob/master/index.js#L28, I believe we need to use `context.lineContent` instead of `context.text`. But I'm not sure about the `.substring(1)` part, of if `lineContent` is always filled when we access `getLineHTMLForExport`.

**Comment by JohnMcLear** [comment]
@lpagliari I think .substring(1) is to remove the prefixed * in the text content.

**Comment by lpagliari** [comment]
sorry, @JohnMcLear, I wasn't clear on my comment. But you are correct, `.substring(1)` is to remove `*`. What I'm not sure is if we need to to call `.substring(1)` for `context.lineContent` or if `lineContent` does not have the `*` prefix. `context.text` has `*` for sure.

**Comment by JohnMcLear** [comment]
I guess @rugk could try ``.lineContent`` to see what problems instead of ``.text``

**Comment by rugk** [comment]
> I guess @rugk could try .lineContent to see what problems instead of .text

For sure, so just changing [this one line](https://github.com/JohnMcLear/ep_headings2/blob/master/index.js#L28)?

**Comment by lpagliari** [comment]
Yes, I believe that's all you need to change, @rugk

**Comment by rugk** [comment]
Okay, just tested it. Nothing changes.

There are still two headlines.

**Comment by rugk** [comment]
Oh wait, that's another issue... :laughing:

**Comment by lpagliari** [comment]
This change will only address the missing text formatting, not the
duplicated lines. And as this is a change on server side, you need to
restart your Etherpad instance.

**Comment by rugk** [comment]
Yes, it basically works. (And it FYI only works in the second heading)
But it sanitises my output, so it actually returns escaped HTML code in the heading now:

```html
<h1>&lt;fs9&gt;M&lt;/fs9&gt;f&lt;fontcourier&gt;d&lt;/fontcourier&gt;fy&lt;s&gt;H&lt;/s&gt;&lt;em&gt;E&lt;/em&gt;&lt;span data-color="blue"&gt;A&lt;/span&gt;&lt;u&gt;D&lt;/u&gt;</h1>
```

Which renders to this:
<h1>&lt;fs9&gt;M&lt;/fs9&gt;f&lt;fontcourier&gt;d&lt;/fontcourier&gt;fy&lt;s&gt;H&lt;/s&gt;&lt;em&gt;E&lt;/em&gt;&lt;span data-color="blue"&gt;A&lt;/span&gt;&lt;u&gt;D&lt;/u&gt;</h1>

**Comment by lpagliari** [comment]
@rugk do you think you can handle this issue?

**Comment by rugk** [comment]
No. I have no idea what's going on. :laughing:

**Comment by JohnMcLear** [comment]
Nor do we.  We figure out what's going on by reading the source code.
